name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build and generate
      run: npm run generate

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .output/public
        branch: main
        token: ${{ secrets.TOKEN }}
        repository-name: m1kx/m1kx.github.io
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: main
        REPO: m1kx/m1kx.github.io
